version: "3.7"
services:
  cpachecker:
    command: scripts/benchmark.py --no-container test/test-sets/legion.xml
    build: .
    volumes:
      - "./src:/usr/app/src"
      - "./doc:/usr/app/doc"
      - "./config:/usr/app/config"
      - "./.vscode:/usr/app/.vscode"
      - "./.devcontainer:/usr/app/.devcontainer"
      - "./.idea:/usr/app/.idea"
